### ISSUE TITLE
Crashes game

### ISSUE THREAD

**Issue by Addablebreak** [JamCoreModding/right-click-harvest#55]
Every time I add this mod to my game it crashes, the other mods I have work fine. Not sure if its a known issue or not.

**Comment by Jamalam360** [comment]
I'll need some more information. If you're on Neoforge, it's known - I accidentally marked the file as compatible

**Comment by Scooodles** [comment]
Same, server crashes when added with the following: 

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'rightclickharvest'!
at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.0.jar:?]
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.0.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.0.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.0.jar:?]
at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.0.jar:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.0.jar:?]
at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: io/github/jamalam360/jamlib/config/ConfigManager
at io.github.jamalam360.rightclickharvest.RightClickHarvest.<clinit>(RightClickHarvest.java:34) ~[rightclickharvest-fabric-1.20.2-4.0.1.jar:?]
at io.github.jamalam360.rightclickharvest.fabriclike.RightClickHarvestFabricLike.init(RightClickHarvestFabricLike.java:7) ~[rightclickharvest-fabric-1.20.2-4.0.1.jar:?]
at io.github.jamalam360.rightclickharvest.fabric.RightClickHarvestFabric.onInitialize(RightClickHarvestFabric.java:14) ~[rightclickharvest-fabric-1.20.2-4.0.1.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.0.jar:?]
... 7 more
Caused by: java.lang.ClassNotFoundException: io.github.jamalam360.jamlib.config.ConfigManager
at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.0.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.0.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
at io.github.jamalam360.rightclickharvest.RightClickHarvest.<clinit>(RightClickHarvest.java:34) ~[rightclickharvest-fabric-1.20.2-4.0.1.jar:?]
at io.github.jamalam360.rightclickharvest.fabriclike.RightClickHarvestFabricLike.init(RightClickHarvestFabricLike.java:7) ~[rightclickharvest-fabric-1.20.2-4.0.1.jar:?]
at io.github.jamalam360.rightclickharvest.fabric.RightClickHarvestFabric.onInitialize(RightClickHarvestFabric.java:14) ~[rightclickharvest-fabric-1.20.2-4.0.1.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.0.jar:?]

**Comment by Jamalam360** [comment]
@Scooodles you didn't have JamLib installed
